name: Deploy On Netlify

on:
      workflow_dispatch:
      inputs:
        Environnement:
          description: 'The Environnement I need to deploy on'
          required: true
          default: '/dev'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
        
      - name: Tests
        run: npm test