name: Deploy On Netlify

on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
        
      - name: Tests
        run: npm test

      - name: Deploy on Netlify
        uses: nwtgck/actions-netlify@v1.0.0
        with:
          publish-dir: ./dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_ID }}
          